fail_fast: true
default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
        exclude: '\.devcontainer/devcontainer\.json$|tsconfig.*\.json$'
      - id: check-toml
      - id: detect-private-key
      - id: check-shebang-scripts-are-executable

  - repo: local
    hooks:
      - id: git-secrets
        name: Git Secrets
        description: git-secrets scans commits, commit messages, and --no-ff merges to prevent adding secrets into your git repositories.
        entry: bash
        args:
          - -c
          - 'git-secrets --pre_commit_hook'
        language: system

      - id: python-pre-commit
        name: Python Pre Commit
        description: Run Python linting and poetry checks
        entry: bash
        args:
          - -c
          - make python-pre-commit
        language: system
