name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  pr_title_format_check:
    name: PR Title Format Check
    uses: NHSDigital/eps-common-workflows/.github/workflows/pr_title_check.yml@8404cf6e3a61ac8de4d1644e175e288aa4965815
    permissions:
      pull-requests: write

  get_asdf_version:
    name: Get asdf Version
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.get_asdf_version.outputs.version }}
    steps:
      - uses: actions/checkout@v6
        name: Checkout source code

      - name: Get asdf version
        id: get_asdf_version
        uses: ./.github/actions/get_asdf_version

  quality_checks:
    name: Quality Checks
    needs: get_asdf_version
    uses: NHSDigital/eps-common-workflows/.github/workflows/quality-checks.yml@141907b215220e95e3ed3811d0fe8fa18675dbed
    with:
      asdfVersion: ${{ needs.get_asdf_version.outputs.version }}
      reinstall_poetry: true
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  tag_release:
    name: Tag Release (Dry Run)
    needs: get_asdf_version
    uses: NHSDigital/eps-common-workflows/.github/workflows/tag-release.yml@141907b215220e95e3ed3811d0fe8fa18675dbed
    with:
      asdfVersion: ${{ needs.get_asdf_version.outputs.version }}
      branch_name: ${{ github.event.pull_request.head.ref }}
      dry_run: true
      pypi_publish: true
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

  dependabot_auto_approve_and_merge:
    name: Dependabot Auto Approve and Merge
    needs: quality_checks
    uses: NHSDigital/eps-common-workflows/.github/workflows/dependabot-auto-approve-and-merge.yml@8404cf6e3a61ac8de4d1644e175e288aa4965815
    permissions:
      contents: write
      pull-requests: write
    secrets:
      AUTOMERGE_APP_ID: ${{ secrets.AUTOMERGE_APP_ID }}
      AUTOMERGE_PEM: ${{ secrets.AUTOMERGE_PEM }}
