name: Pull Request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: {}
jobs:
  pr_title_format_check:
    name: PR Title Format Check
    uses: NHSDigital/eps-common-workflows/.github/workflows/pr_title_check.yml@e798d5aee897de6f7dc387dd5623fcd9ba4c8929
    permissions:
      pull-requests: write
  get_config_values:
    uses: NHSDigital/eps-common-workflows/.github/workflows/get-repo-config.yml@e798d5aee897de6f7dc387dd5623fcd9ba4c8929
    permissions:
      attestations: read
      contents: read
      packages: read
    with:
      verify_published_from_main_image: false


  get_pypi_token:
    name: Get PyPI Token for Trusted Publishing
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    outputs:
      pypi_token: ${{ steps.get_pypi_token.outputs.pypi_token }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        name: Checkout source code
        with:
          persist-credentials: false

      - name: Get PyPI token
        id: get_pypi_token
        uses: ./.github/actions/get_pypi_token

  quality_checks:
    name: Quality Checks
    needs: get_config_values
    uses: NHSDigital/eps-common-workflows/.github/workflows/quality-checks-devcontainer.yml@8399c1f015c1304e40771cbd8ccc24c7ed48fdbc
    permissions:
      contents: read
      id-token: write
      packages: read
    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  tag_release:
    name: Tag Release (Dry Run)
    needs: [get_config_values, get_pypi_token]
    uses: NHSDigital/eps-common-workflows/.github/workflows/tag-release-devcontainer.yml@e798d5aee897de6f7dc387dd5623fcd9ba4c8929
    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
      branch_name: ${{ github.event.pull_request.head.ref }}
      dry_run: true
      pypi_publish: true
    secrets:
      PYPI_TOKEN: ${{ needs.get_pypi_token.outputs.pypi_token }}
    permissions:
      id-token: write
      contents: write
      packages: write

  dependabot_auto_approve_and_merge:
    name: Dependabot Auto Approve and Merge
    needs: quality_checks
    uses: NHSDigital/eps-common-workflows/.github/workflows/dependabot-auto-approve-and-merge.yml@e798d5aee897de6f7dc387dd5623fcd9ba4c8929
    permissions:
      contents: write
      pull-requests: write
    secrets:
      AUTOMERGE_APP_ID: ${{ secrets.AUTOMERGE_APP_ID }}
      AUTOMERGE_PEM: ${{ secrets.AUTOMERGE_PEM }}
